### ISSUE TITLE
How do I remove this?

### ISSUE THREAD

**Issue by liamfoneill** [pbatard/uefi-ntfs#23]
I installed Windows with Rufus once which created the disk 'UEFI_NTFS' but have subsuently reinstalled Windows a number of times using the Windows Media Creation Tool (not Rufus). How do I safely remove this 512kb 'UEFI_NTFS'? 

![image](https://user-images.githubusercontent.com/1243172/102619243-0a30b080-4134-11eb-9d0f-5e109e995c95.png)

**Comment by pbatard** [comment]
The checklist is not optional. If you had followed it you would have found [this entry from the FAQ](https://github.com/pbatard/rufus/wiki/FAQ#Help_how_do_I_restore_my_USB_to_how_it_was_before_I_created_a_bootable_drive) that answers your question.

**Comment by pbatard** [comment]
Ah, sorry, you logged this in uefi-ntfs where there is no checklist, rather than Rufus. But if you had an issue with what Rufus did, you should have created an issue under the Rufus project, not UEFI:NTFS, since it was Rufus that installed that partition.
