### ISSUE TITLE
Repair uefi-ntfs partition

### ISSUE THREAD

**Issue by everestbrooks** [pbatard/uefi-ntfs#27]
I have a W2G 20H2 image with both legacy and uefi boot that displays the error "Please wait" when I attempt to boot from the uefi-ntfs partition. Is there any way to repair the uefi-ntfs partition? I had this working for a few months but it stopped working today after a Windows update. This has happened before and the only thing I could do was reimage the drive. 
Thanks,

**Comment by pbatard** [comment]
> Is there any way to repair the uefi-ntfs partition?

As mentioned in the README:

> You can find a ready-to-use FAT partition image, containing the x86 and ARM versions of the UEFI:NTFS loader (both 32 and 64 bit) and driver in the Rufus project, under [/res/uefi](https://github.com/pbatard/rufus/tree/master/res/uefi).
>
> If you create a partition of the same size at the end of your drive and copy [`uefi-ntfs.img`](https://github.com/pbatard/rufus/blob/master/res/uefi/uefi-ntfs.img?raw=true) there (in DD mode of course), then you should have everything you need to make the first NTFS partition on that drive UEFI bootable.

In other words, you should be able to just pick the `uefi-ntfs.img` linked above and write it at the end of your drive, provided that you have a partition of the same size existing there (which I expect to be the case).
