### ISSUE TITLE
Trojan ?

### ISSUE THREAD

**Issue by gtbu** [pbatard/uefi-ntfs#38]
Iobit malwarefighter (with Bitdefender) says about uefi-ntfs 2.3.zip  that debug.vbs has a Trojan.Valyria.3926

**Comment by pbatard** [comment]
Please report the __false positive__ to BitDefender.

See also https://github.com/pbatard/rufus/wiki/FAQ#user-content-Antivirus_X_reports_that_Rufus_contains_malware that applies to both Rufus and UEFI:NTFS.

For reference, the UEFI:NTFS full source is available here and the executable from the zip, which is built from GitHub actions, can be formally demonstrated as having been built from the public source.

Therefore, unless BitDefender can point to where exactly in its __very small__ source UEFI:NTFS includes a UEFI trojan, this is yet another in a long list of false positives that I genuinely don't have time to chase.
