### ISSUE TITLE
Stuck @ This Screen (Rufus v3.22) (UEFI + GPT + NTFS)

### ISSUE THREAD

**Issue by casioforever** [pbatard/uefi-ntfs#39]
![ab7e8cc5-96c6-41a7-b21d-ae2ff8243105](https://github.com/pbatard/uefi-ntfs/assets/148558396/414a3c88-4ce7-4a10-9b55-7bab6ec47e72)

Windows 7 ultimate Iso
INSTALL.WIM = 4.56 GB
No CSM - Windows 10 OS Support
Legacy USB Support = Enabled

**Comment by pbatard** [comment]
Please don't double post.
