### ISSUE TITLE
Does UEFI-NTFS support Linux?

### ISSUE THREAD

**Issue by yangxuan8282** [pbatard/uefi-ntfs#4]
I am trying to make a bootable linux usb, the usb disk is in NTFS format.
First I put the system files include **/EFI** folder into NTFS partiton. Then create a FAT partition at the end of drive, and copy the file from [uefi_ntfs.img](https://github.com/pbatard/rufus/blob/master/res/uefi/uefi-ntfs.img?raw=true). 
 
But when I reboot to UEFI boot option, just got a minimal bash like this

    grub>

Did I miss something?

**Comment by pbatard** [comment]
The fact that you get the `grub>` prompt means that UEFI:NTFS is working exactly as expected.

This means that UEFI:NTFS was successfully able to launch GRUB on your NTFS partition.

Now, if GRUB doesn't boot from NTFS, that's entirely a GRUB problem not an NTFS one. Be mindful that most bootloaders (as well as Linux boot systems) do __not__ support reading from an NTFS file system by default. So, for instance, if GRUB is configured to load a component from the file system, but doesn't have the NTFS module, it will of course fail to load. Likewise, even if GRUB manages to load and launch your kernel, if the Linux init loader attempts to load a file from the filesystem, but doesn't have NTFS support, it will fail.

Considering that your issue has nothing to do with UEFI:NTFS (which, again, worked exactly as designed), I will close it.
