### ISSUE TITLE
What will be use case of R/W NTFS Driver over Read-only NTFS Driver ?

### ISSUE THREAD

**Issue by devdevadev** [pbatard/uefi-ntfs#42]
Happly New Year....

Thanks for quick reply....and explaining the side effect of the requested feature.

Now I have to go with .cmd approach to choose desired ISO out of multiple Windows ISOs in NTFS Partition 1 after booting from UEFI:NTFS from Partition 3 of USB Drive....

BTW, Thanks for the UEFI:NTFS development.......

Why you want to sign R/W NTFS Driver ? What exactly will be the use case of R/W NTFS Driver over read-only NTFS Driver ?

What will be extra benefit of R/W NTFS Driver in UEFI::NTFS / Rufus ?

Regards..

_Originally posted by @devdevadev in https://github.com/pbatard/uefi-ntfs/issues/41#issuecomment-1873354284_

**Comment by pbatard** [comment]
That's the point: I went out of my way to do **extra work** to simplify the drive and **remove** a feature, that was available, but that introduced extra code that would see little to no use.

Therefore, similarly, I do not want to add the feature you request, as it is irrelevant to the purpose of UEFI:NTFS.
