### ISSUE TITLE
Not booting the boot manager.

### ISSUE THREAD

**Issue by kristiandyan** [pbatard/uefi-ntfs#46]
I've been stuck on this error for months. Any idea what could have happened? I removed all of the connection including ssd's rams and reset the bios. I need help 🥹
![PXL_20240725_070620385 MV](https://github.com/user-attachments/assets/266c4068-166e-4dc4-9ca6-1c661bf74eda)

**Comment by pbatard** [comment]
For a start, It'd help if you told the manufacturer, model of your PC as well as the BIOS version.

But really, once Windows bootmgr starts, the boot process is 100% in the hands of Microsoft, so my guess is an incompatibility between your specific hardware/BIOS and the Microsoft bootloader.

**Comment by kristiandyan** [comment]
Thanks so much. I appreciate the time. I just installed windows using CMD with two USB 1 rufus and 1 ventoy which is really weird. Anyways, keep up the good work!!! 😊

**Comment by pbatard** [comment]
Closing this issue, as there is no further update.
