### ISSUE TITLE
how to update a usb key with latest uefi-ntfs

### ISSUE THREAD

**Issue by asdffdsazqqq** [pbatard/uefi-ntfs#47]
hello, thanks, the software is working perfectly.

i have a usb key using an old version, `2.2` that i installed using rufus.
now, i cannot figure out how to update to latest, `2.5`

thanks much, david

**Comment by pbatard** [comment]
Please don't cross post. Answerd in pbatard/rufus#2555.

You don't update UEFI:NTFS manually. You just recreate the media.
