### ISSUE TITLE
Example on Windows and/or Linux

### ISSUE THREAD

**Issue by RomelSan** [pbatard/uefi-ntfs#9]
Hi,
How can i make an USB flash drive with NTFS and FAT32 partitions with UEFI-NTFS img from a Windows Pc?

I am thinking: 
1) Create a NTFS partition using diskpart and leave a little space at the end.
2) With other partition software ex: Easus Partition Home i create a Fat32 partition.
3) Using dd for windows i copy/burn the image to the USB fat32 partition.
4) Copy the windows ISO contents to the NTFS partition.

Will this work?
Is there an easier method (manual)?

I know that Rufus is working fine, but i want to know how to do this manually, for the sake of knowledge.
Thanks 👍

**Comment by pbatard** [comment]
It's in the README:

> If you create a partition of the same size at the end of your drive and copy [`uefi-ntfs.img`](https://github.com/pbatard/rufus/blob/master/res/uefi/uefi-ntfs.img?raw=true) there (in DD mode of course), then you should have everything you need to make the first NTFS partition on that drive UEFI bootable.

So you just need to have a 256KB partition at the end of your drive (type generic data I think &mdash; can't recall the exact GPT denomination but your partitioning software should list the choices), `dd` that .img onto it, and you're good to go.
